#!  Data Modeller Enterprise Edition
#!
#!
#TEMPLATE(DataModeller,'Data Modeller Templates')
#!
#EXTENSION(DataModeller,'Add Global File Variables'),APPLICATION
 #BOXED('Data Modeller Varaible Definitions')
  #Image('Pea.bmp')
  #DISPLAY('')
  #DISPLAY('Presented By Pea Brain Software cc')
  #DISPLAY('© R J Du Preez. 1998')
  #DISPLAY('All Rights Reserved')
  #DISPLAY('WARNING')
  #DISPLAY('This Template is protected by copyright and international')
  #DISPLAY('law and treaties. Unauthorized reproduction or distribution')
  #DISPLAY('of this template or any part thereof, may result in severe ')
  #DISPLAY('civil and criminal penalties, and will be prosecuted to the')
  #DISPLAY('maximum extend possible under the law.')
  #DISPLAY('Address: eMail:peabrain@global.co.za')
  #DISPLAY('')
 #ENDBOXED

 #AT(%BeforeFileDeclarations)
 Include('DMGloVar.INC'),LIST
 #ENDAT
