package org.jclarion.clarion.test.simpleapp;

import org.jclarion.clarion.constants.Font;
import org.jclarion.clarion.constants.Std;
import org.jclarion.clarion.ClarionNumber;
import org.jclarion.clarion.ClarionString;
import org.jclarion.clarion.ClarionWindow;
import org.jclarion.clarion.control.ButtonControl;
import org.jclarion.clarion.control.GroupControl;
import org.jclarion.clarion.control.PanelControl;
import org.jclarion.clarion.control.StringControl;

public class Window_59 extends ClarionWindow
{
	public int _spareparts=0;
	public int _workshop=0;
	public int _units=0;
	public int _accounts=0;
	public int _group1_9=0;
	public int _string1T_9=0;
	public int _accounts_2=0;
	public int _group1_7=0;
	public int _string1T_7=0;
	public int _miner=0;
	public int _group1_8=0;
	public int _string1T_8=0;
	public int _miner_2=0;
	public int _setup=0;
	public int _button2=0;
	public int _panel1=0;
	public int _heading=0;
	public int _string11=0;
	public int _office=0;
	public int _string6=0;
	public int _usrName_2=0;
	public int _string12=0;
	public int _support=0;
	public int _string9=0;
	public int _dtoday=0;
	public int _string13=0;
	public int _mobile=0;
	public int _string5=0;
	public int _group1=0;
	public int _string1T=0;
	public int _group1_2=0;
	public int _string1T_2=0;
	public int _group1_6=0;
	public int _string1T_6=0;
	public int _group1_5=0;
	public int _string1T_5=0;
	public int _group1_3=0;
	public int _string1T_3=0;
	public int _group1_4=0;
	public int _string1T_4=0;
	public Window_59(ClarionString heading,ClarionNumber dtoday)
	{
		this.setText("Main Menu").setAt(null,null,331,269).setFont("MS Sans Serif",8,null,Font.REGULAR,null).setIcon("D:\\C8SYS\\cvsapak\\main\\images\\bike.ico").setTimer(6000).setSystem().setGray().setDouble().setMDI().setImmediate();
		this.setId("mainmenu.window");
		ButtonControl _C1=new ButtonControl();
		_C1.setText("Spare &Parts").setAt(29,47,107,21).setFont(null,12,null,Font.BOLD,null);
		this._spareparts=this.register(_C1,"mainmenu.window.spareparts");
		this.add(_C1);
		ButtonControl _C2=new ButtonControl();
		_C2.setText("&Workshop").setAt(29,71,107,21).setFont(null,12,null,Font.BOLD,null);
		this._workshop=this.register(_C2,"mainmenu.window.workshop");
		this.add(_C2);
		ButtonControl _C3=new ButtonControl();
		_C3.setText("&Units").setAt(30,95,107,21).setFont(null,12,null,Font.BOLD,null);
		_C3.setProperty(31744,"&Units");
		this._units=this.register(_C3,"mainmenu.window.units");
		this.add(_C3);
		ButtonControl _C4=new ButtonControl();
		_C4.setText("&Accounts").setAt(30,121,107,21).setFont(null,12,null,Font.BOLD,null);
		this._accounts=this.register(_C4,"mainmenu.window.accounts");
		this.add(_C4);
		GroupControl _C5=new GroupControl();
		_C5.setAt(141,141,162,25).setBoxed();
		this._group1_9=this.register(_C5,"mainmenu.window.group1:9");
		this.add(_C5);
		StringControl _C6=new StringControl();
		_C6.setText("Lookup Accounts / Franchises and Suppliers").setAt(145,149,null,null);
		this._string1T_9=this.register(_C6,"mainmenu.window.string1:t:9");
		_C5.add(_C6);
		ButtonControl _C7=new ButtonControl();
		_C7.setText("P&honebook").setAt(29,145,107,21).setFont(null,12,null,Font.BOLD,null);
		this._accounts_2=this.register(_C7,"mainmenu.window.accounts:2");
		this.add(_C7);
		GroupControl _C8=new GroupControl();
		_C8.setAt(142,167,162,25).setBoxed();
		this._group1_7=this.register(_C8,"mainmenu.window.group1:7");
		this.add(_C8);
		StringControl _C9=new StringControl();
		_C9.setText("Data Query, Export and Mail Merge").setAt(146,178,null,null);
		this._string1T_7=this.register(_C9,"mainmenu.window.string1:t:7");
		_C8.add(_C9);
		ButtonControl _C10=new ButtonControl();
		_C10.setText("&Miner").setAt(30,171,107,21).setFont(null,12,null,Font.BOLD,null);
		this._miner=this.register(_C10,"mainmenu.window.miner");
		this.add(_C10);
		GroupControl _C11=new GroupControl();
		_C11.setAt(142,191,162,25).setBoxed();
		this._group1_8=this.register(_C11,"mainmenu.window.group1:8");
		this.add(_C11);
		StringControl _C12=new StringControl();
		_C12.setText("Entire business concerns. Business Activity").setAt(146,199,null,null);
		this._string1T_8=this.register(_C12,"mainmenu.window.string1:t:8");
		_C11.add(_C12);
		ButtonControl _C13=new ButtonControl();
		_C13.setText("&Business").setAt(30,195,107,21).setFont(null,12,null,Font.BOLD,null);
		this._miner_2=this.register(_C13,"mainmenu.window.miner:2");
		this.add(_C13);
		ButtonControl _C14=new ButtonControl();
		_C14.setText("&Setup").setAt(30,218,107,21).setFont(null,12,null,Font.BOLD,null);
		this._setup=this.register(_C14,"mainmenu.window.setup");
		this.add(_C14);
		ButtonControl _C15=new ButtonControl();
		_C15.setText("E&xit").setAt(30,244,107,21).setFont(null,12,null,Font.BOLD,null).setStandard(Std.CLOSE);
		this._button2=this.register(_C15,"mainmenu.window.button2");
		this.add(_C15);
		PanelControl _C16=new PanelControl();
		_C16.setAt(3,1,324,43);
		this._panel1=this.register(_C16,"mainmenu.window.panel1");
		this.add(_C16);
		StringControl _C17=new StringControl();
		_C17.setPicture("@s60").setAt(8,3,315,10).setCenter(null).setFont(null,null,null,Font.BOLD,null);
		this._heading=this.register(_C17.use(heading),"mainmenu.window.heading");
		this.add(_C17);
		StringControl _C18=new StringControl();
		_C18.setText("Office:").setAt(222,12,56,10).setRight(null);
		this._string11=this.register(_C18,"mainmenu.window.string11");
		this.add(_C18);
		StringControl _C19=new StringControl();
		_C19.setText("03 5422 2255").setAt(280,12,null,null).setLeft(null);
		this._office=this.register(_C19,"mainmenu.window.office");
		this.add(_C19);
		StringControl _C20=new StringControl();
		_C20.setText("Registered To:").setAt(7,20,null,null);
		this._string6=this.register(_C20,"mainmenu.window.string6");
		this.add(_C20);
		StringControl _C21=new StringControl();
		_C21.setPicture("@s40").setAt(58,20,163,null);
		this._usrName_2=this.register(_C21.use(Main.name_2),"mainmenu.window.usr:name_2");
		this.add(_C21);
		StringControl _C22=new StringControl();
		_C22.setText("Support (Dave):").setAt(222,22,56,10).setRight(null);
		this._string12=this.register(_C22,"mainmenu.window.string12");
		this.add(_C22);
		StringControl _C23=new StringControl();
		_C23.setText("0418 107 007").setAt(280,22,null,10).setLeft(null);
		this._support=this.register(_C23,"mainmenu.window.support");
		this.add(_C23);
		StringControl _C24=new StringControl();
		_C24.setText("Today's Date:").setAt(7,31,null,null);
		this._string9=this.register(_C24,"mainmenu.window.string9");
		this.add(_C24);
		StringControl _C25=new StringControl();
		_C25.setPicture("@D6").setAt(58,31,null,null);
		this._dtoday=this.register(_C25.use(dtoday),"mainmenu.window.dtoday");
		this.add(_C25);
		StringControl _C26=new StringControl();
		_C26.setText("Support (Barney):").setAt(222,33,56,10).setRight(null);
		this._string13=this.register(_C26,"mainmenu.window.string13");
		this.add(_C26);
		StringControl _C27=new StringControl();
		_C27.setText("0422 206 974").setAt(280,33,null,null).setLeft(null);
		this._mobile=this.register(_C27,"mainmenu.window.mobile");
		this.add(_C27);
		StringControl _C28=new StringControl();
		_C28.setText("").setAt(287,39,null,null);
		this._string5=this.register(_C28,"mainmenu.window.string5");
		this.add(_C28);
		GroupControl _C29=new GroupControl();
		_C29.setAt(141,43,162,25).setBoxed();
		this._group1=this.register(_C29,"mainmenu.window.group1");
		this.add(_C29);
		StringControl _C30=new StringControl();
		_C30.setText("Spare Parts Management").setAt(145,51,null,null);
		this._string1T=this.register(_C30,"mainmenu.window.string1:t");
		_C29.add(_C30);
		GroupControl _C31=new GroupControl();
		_C31.setAt(141,67,162,25).setBoxed();
		this._group1_2=this.register(_C31,"mainmenu.window.group1:2");
		this.add(_C31);
		StringControl _C32=new StringControl();
		_C32.setText("Workshop").setAt(145,75,null,null);
		this._string1T_2=this.register(_C32,"mainmenu.window.string1:t:2");
		_C31.add(_C32);
		GroupControl _C33=new GroupControl();
		_C33.setAt(142,116,162,25).setBoxed();
		this._group1_6=this.register(_C33,"mainmenu.window.group1:6");
		this.add(_C33);
		StringControl _C34=new StringControl();
		_C34.setText("Accounts").setAt(146,124,null,null);
		this._string1T_6=this.register(_C34,"mainmenu.window.string1:t:6");
		_C33.add(_C34);
		GroupControl _C35=new GroupControl();
		_C35.setAt(142,91,162,25).setBoxed();
		this._group1_5=this.register(_C35,"mainmenu.window.group1:5");
		this.add(_C35);
		StringControl _C36=new StringControl();
		_C36.setText("Units").setAt(146,99,null,null);
		this._string1T_5=this.register(_C36,"mainmenu.window.string1:t:5");
		_C35.add(_C36);
		GroupControl _C37=new GroupControl();
		_C37.setAt(142,215,162,25).setBoxed();
		this._group1_3=this.register(_C37,"mainmenu.window.group1:3");
		this.add(_C37);
		StringControl _C38=new StringControl();
		_C38.setText("Application Setup").setAt(146,223,null,null);
		this._string1T_3=this.register(_C38,"mainmenu.window.string1:t:3");
		_C37.add(_C38);
		GroupControl _C39=new GroupControl();
		_C39.setAt(142,241,162,25).setBoxed();
		this._group1_4=this.register(_C39,"mainmenu.window.group1:4");
		this.add(_C39);
		StringControl _C40=new StringControl();
		_C40.setText("Exit Application").setAt(146,249,null,null);
		this._string1T_4=this.register(_C40,"mainmenu.window.string1:t:4");
		_C39.add(_C40);
	}
}
