package clarion.invoi001;

import clarion.Main;
import clarion.equates.Color;
import clarion.equates.Font;
import clarion.equates.Icon;
import clarion.equates.Std;
import clarion.invoi001.QueueBrowse_1_3;
import org.jclarion.clarion.ClarionString;
import org.jclarion.clarion.ClarionWindow;
import org.jclarion.clarion.control.ButtonControl;
import org.jclarion.clarion.control.GroupControl;
import org.jclarion.clarion.control.ListControl;
import org.jclarion.clarion.control.SheetControl;
import org.jclarion.clarion.control.StringControl;
import org.jclarion.clarion.control.TabControl;

@SuppressWarnings("all")
public class Quickwindow_6 extends ClarionWindow
{
	public int _currenttab=0;
	public int _tab_2=0;
	public int _string7=0;
	public int _cusLastname=0;
	public int _tab_3=0;
	public int _string12=0;
	public int _cusCompany=0;
	public int _tab_4=0;
	public int _string13=0;
	public int _cusZipcode=0;
	public int _tab_5=0;
	public int _cusState=0;
	public int _string14=0;
	public int _browse_1=0;
	public int _select_2=0;
	public int _insert_3=0;
	public int _change_3=0;
	public int _delete_3=0;
	public int _help=0;
	public int _group1=0;
	public int _string1=0;
	public int _cusAddress1=0;
	public int _cusAddress2=0;
	public int _glotCuscsz=0;
	public int _pstring=0;
	public int _cusPhonenumber=0;
	public int _print=0;
	public int _query=0;
	public int _bobutton=0;
	public int _close=0;
	public int _toolbox=0;
	public Quickwindow_6(QueueBrowse_1_3 queueBrowse_1)
	{
		this.setText("Browse Customers").setAt(null,null,322,221).setFont("MS Sans Serif",8,null,null,null).setImmediate().setIcon("CUSTOMER.ICO").setHelp("~BrowseCustomers").setSystem().setGray().setResize().setMDI();
		this.setId("browsecustomers.quickwindow");
		SheetControl _C1=new SheetControl();
		_C1.setAt(5,1,313,162);
		this._currenttab=this.register(_C1,"browsecustomers.quickwindow.currenttab");
		this.add(_C1);
		TabControl _C2=new TabControl();
		_C2.setText("FullName");
		this._tab_2=this.register(_C2,"browsecustomers.quickwindow.tab:2");
		_C1.add(_C2);
		StringControl _C3=new StringControl();
		_C3.setText("Locator: Lastname").setAt(11,20,77,10).setFont("MS Sans Serif",8,null,Font.BOLD,null);
		this._string7=this.register(_C3,"browsecustomers.quickwindow.string7");
		_C2.add(_C3);
		StringControl _C4=new StringControl();
		_C4.setPicture("@s25").setAt(92,20,104,10).setTransparent().setFont(null,null,Color.RED,Font.BOLD,null);
		this._cusLastname=this.register(_C4.use(Main.customers.lastname),"browsecustomers.quickwindow.cus:lastname");
		_C2.add(_C4);
		TabControl _C5=new TabControl();
		_C5.setText("Company");
		this._tab_3=this.register(_C5,"browsecustomers.quickwindow.tab:3");
		_C1.add(_C5);
		StringControl _C6=new StringControl();
		_C6.setText("Locator: Company").setAt(13,20,73,10).setFont(null,null,null,Font.BOLD,null);
		this._string12=this.register(_C6,"browsecustomers.quickwindow.string12");
		_C5.add(_C6);
		StringControl _C7=new StringControl();
		_C7.setPicture("@s20").setAt(90,20,83,10).setTransparent().setFont(null,null,Color.RED,Font.BOLD,null);
		this._cusCompany=this.register(_C7.use(Main.customers.company),"browsecustomers.quickwindow.cus:company");
		_C5.add(_C7);
		TabControl _C8=new TabControl();
		_C8.setText("ZipCode");
		this._tab_4=this.register(_C8,"browsecustomers.quickwindow.tab:4");
		_C1.add(_C8);
		StringControl _C9=new StringControl();
		_C9.setText("Locator:  Zipcode").setAt(11,20,71,10).setFont(null,null,null,Font.BOLD,null);
		this._string13=this.register(_C9,"browsecustomers.quickwindow.string13");
		_C8.add(_C9);
		StringControl _C10=new StringControl();
		_C10.setPicture("@K#####|-####KB").setAt(87,20,51,10).setTransparent().setFont(null,null,Color.RED,Font.BOLD,null);
		this._cusZipcode=this.register(_C10.use(Main.customers.zipcode),"browsecustomers.quickwindow.cus:zipcode");
		_C8.add(_C10);
		TabControl _C11=new TabControl();
		_C11.setText("State");
		this._tab_5=this.register(_C11,"browsecustomers.quickwindow.tab:5");
		_C1.add(_C11);
		StringControl _C12=new StringControl();
		_C12.setPicture("@s2").setAt(73,20,26,10).setTransparent().setCenter(null).setFont(null,null,Color.RED,Font.BOLD,null);
		this._cusState=this.register(_C12.use(Main.customers.state),"browsecustomers.quickwindow.cus:state");
		_C11.add(_C12);
		StringControl _C13=new StringControl();
		_C13.setText("Locator: State").setAt(12,20,62,10).setFont(null,null,null,Font.BOLD,null);
		this._string14=this.register(_C13,"browsecustomers.quickwindow.string14");
		_C11.add(_C13);
		ListControl _C14=new ListControl();
		_C14.setVScroll().setFormat(ClarionString.staticConcat("63L(2)|M~First Name~@s20@14C|M~MI~L(1)@s1@63L(2)|M~Last Name~@s25@71L(2)|M~Compa","ny~@s20@22C|M~State~L(1)@s2@80L(1)|M~Zip Code~L(2)@K#####|-####KB@")).setFrom(queueBrowse_1).setAt(12,33,301,124).setImmediate().setMsg("Browsing Records");
		this._browse_1=this.register(_C14,"browsecustomers.quickwindow.browse:1");
		this.add(_C14);
		ButtonControl _C15=new ButtonControl();
		_C15.setText("&Select").setAt(193,113,28,14).setHidden();
		this._select_2=this.register(_C15,"browsecustomers.quickwindow.select:2");
		this.add(_C15);
		ButtonControl _C16=new ButtonControl();
		_C16.setText("&Insert").setAt(159,113,27,14).setHidden();
		this._insert_3=this.register(_C16,"browsecustomers.quickwindow.insert:3");
		this.add(_C16);
		ButtonControl _C17=new ButtonControl();
		_C17.setDefault().setText("&Change").setAt(93,114,25,14).setHidden();
		this._change_3=this.register(_C17,"browsecustomers.quickwindow.change:3");
		this.add(_C17);
		ButtonControl _C18=new ButtonControl();
		_C18.setText("&Delete").setAt(253,113,30,14).setHidden();
		this._delete_3=this.register(_C18,"browsecustomers.quickwindow.delete:3");
		this.add(_C18);
		ButtonControl _C19=new ButtonControl();
		_C19.setIcon(Icon.HELP).setAt(132,112,15,14).setHidden().setTip("Get Help").setStandard(Std.HELP);
		this._help=this.register(_C19,"browsecustomers.quickwindow.help");
		this.add(_C19);
		GroupControl _C20=new GroupControl();
		_C20.setAt(6,167,177,52).setBoxed().setBevel(2,-1,null);
		this._group1=this.register(_C20,"browsecustomers.quickwindow.group1");
		this.add(_C20);
		StringControl _C21=new StringControl();
		_C21.setText("Customer's Address").setAt(10,169,150,10).setLeft(2).setFont("MS Sans Serif",10,Color.NAVY,Font.BOLD+Font.UNDERLINE,null);
		this._string1=this.register(_C21,"browsecustomers.quickwindow.string1");
		_C20.add(_C21);
		StringControl _C22=new StringControl();
		_C22.setPicture("@s35").setAt(10,180,169,9).setFont(null,null,Color.TEAL,Font.BOLD,null);
		this._cusAddress1=this.register(_C22.use(Main.customers.address1),"browsecustomers.quickwindow.cus:address1");
		_C20.add(_C22);
		StringControl _C23=new StringControl();
		_C23.setPicture("@s35").setAt(10,188,167,9).setFont(null,null,Color.TEAL,Font.BOLD,null);
		this._cusAddress2=this.register(_C23.use(Main.customers.address2),"browsecustomers.quickwindow.cus:address2");
		_C20.add(_C23);
		StringControl _C24=new StringControl();
		_C24.setPicture("@s40").setAt(10,196,169,11).setFont(null,null,Color.TEAL,Font.BOLD,null);
		this._glotCuscsz=this.register(_C24.use(Main.glotCuscsz),"browsecustomers.quickwindow.glot:cuscsz");
		_C20.add(_C24);
		StringControl _C25=new StringControl();
		_C25.setText("Phone Number:").setAt(10,206,64,10).setFont(null,null,Color.NAVY,Font.BOLD,null);
		this._pstring=this.register(_C25,"browsecustomers.quickwindow.pstring");
		_C20.add(_C25);
		StringControl _C26=new StringControl();
		_C26.setPicture("@P(###) ###-####PB").setAt(73,206,72,10).setCenter(null).setFont(null,null,Color.TEAL,Font.BOLD,null);
		this._cusPhonenumber=this.register(_C26.use(Main.customers.phonenumber),"browsecustomers.quickwindow.cus:phonenumber");
		_C20.add(_C26);
		ButtonControl _C27=new ButtonControl();
		_C27.setFlat().setText("&Print").setAt(187,168,42,14).setSkip().setFont(null,null,Color.NAVY,Font.BOLD,null).setTip("Print selected customer info");
		this._print=this.register(_C27,"browsecustomers.quickwindow.print");
		this.add(_C27);
		ButtonControl _C28=new ButtonControl();
		_C28.setFlat().setText("&Query").setAt(187,186,42,14).setSkip().setFont(null,null,Color.NAVY,Font.BOLD,null).setTip("Query by example");
		this._query=this.register(_C28,"browsecustomers.quickwindow.query");
		this.add(_C28);
		ButtonControl _C29=new ButtonControl();
		_C29.setIcon("NOTE14.ICO").setFlat().setText("Orders").setAt(239,175,36,39).setSkip().setFont("MS Sans Serif",8,Color.NAVY,Font.BOLD,null).setMsg("Browse the selected Customer's Orders").setTip("Browse the selected Customer's Orders");
		this._bobutton=this.register(_C29,"browsecustomers.quickwindow.bobutton");
		this.add(_C29);
		ButtonControl _C30=new ButtonControl();
		_C30.setIcon("EXITS.ICO").setFlat().setText("Close").setAt(281,175,36,39).setSkip().setFont("MS Sans Serif",8,Color.NAVY,Font.BOLD,null).setTip("Exit browse");
		this._close=this.register(_C30,"browsecustomers.quickwindow.close");
		this.add(_C30);
		ButtonControl _C31=new ButtonControl();
		_C31.setFlat().setText("&Toolbox").setAt(187,204,null,null).setSkip().setFont(null,null,Color.NAVY,Font.BOLD,null).setTip("Floating toolbox");
		this._toolbox=this.register(_C31,"browsecustomers.quickwindow.toolbox");
		this.add(_C31);
	}
}
