package clarion.invoi002;

import clarion.Main;
import clarion.equates.Color;
import clarion.equates.Font;
import org.jclarion.clarion.ClarionReport;
import org.jclarion.clarion.control.BoxControl;
import org.jclarion.clarion.control.ReportBreak;
import org.jclarion.clarion.control.ReportDetail;
import org.jclarion.clarion.control.ReportFooter;
import org.jclarion.clarion.control.ReportHeader;
import org.jclarion.clarion.control.StringControl;

@SuppressWarnings("all")
public class Report extends ClarionReport
{
	public int _string16=0;
	public int _box1=0;
	public int _string11=0;
	public int _string15=0;
	public int _string13=0;
	public int _string14=0;
	public int _cusState=0;
	public int _detail=0;
	public int _cusZipcode=0;
	public int _glotCustname=0;
	public int _cusExtension=0;
	public int _cusCity=0;
	public int _cusCompany=0;
	public int _cusPhonenumber=0;
	public int _pagecount=0;
	public ReportBreak break1=null;
	public ReportDetail detail=null;
	public Report()
	{
		this.setAt(490,1167,7510,9104).setFont("MS Serif",8,null,Font.REGULAR,null).setThous();
		ReportHeader _C1=new ReportHeader();
		_C1.setAt(500,500,7490,667);
		this.add(_C1);
		StringControl _C2=new StringControl();
		_C2.setText("Customers By State").setAt(21,10,7458,354).setCenter(null).setFont("MS Serif",18,null,Font.BOLD,null);
		this._string16=this.register(_C2);
		_C1.add(_C2);
		BoxControl _C3=new BoxControl();
		_C3.setRound().setAt(10,385,7490,292).setColor(Color.BLACK,null,null);
		this._box1=this.register(_C3);
		_C1.add(_C3);
		StringControl _C4=new StringControl();
		_C4.setText("Name").setAt(42,458,1813,167).setTransparent().setFont("MS Serif",10,null,Font.REGULAR,null);
		_C1.add(_C4);
		StringControl _C5=new StringControl();
		_C5.setText("Company").setAt(2052,458,1021,167).setTransparent().setFont("MS Serif",10,null,Font.REGULAR,null);
		_C1.add(_C5);
		StringControl _C6=new StringControl();
		_C6.setText("City").setAt(3271,458,1240,167).setTransparent().setFont("MS Serif",10,null,Font.REGULAR,null);
		this._string11=this.register(_C6);
		_C1.add(_C6);
		StringControl _C7=new StringControl();
		_C7.setText("Zipcode").setAt(4771,458,615,167).setTransparent().setFont("MS Serif",10,null,Font.REGULAR,null);
		this._string15=this.register(_C7);
		_C1.add(_C7);
		StringControl _C8=new StringControl();
		_C8.setText("Phone#").setAt(5729,458,729,167).setTransparent().setFont("MS Serif",10,null,Font.REGULAR,null);
		this._string13=this.register(_C8);
		_C1.add(_C8);
		StringControl _C9=new StringControl();
		_C9.setText("Extension").setAt(6688,458,698,167).setTransparent().setFont("MS Serif",10,null,null,null);
		this._string14=this.register(_C9);
		_C1.add(_C9);
		this.break1=new ReportBreak();
		this.break1.setVariable(Main.customers.state);
		this.add(this.break1);
		ReportHeader _C10=new ReportHeader();
		_C10.setAt(0,0,7510,354);
		this.break1.add(_C10);
		StringControl _C11=new StringControl();
		_C11.setPicture("@s2").setAt(63,73,594,240).setFont("MS Serif",14,null,Font.BOLD+Font.UNDERLINE,null);
		this._cusState=this.register(_C11.use(Main.customers.state));
		_C10.add(_C11);
		this.detail=new ReportDetail();
		this.detail.setAt(10,10,7510,250);
		this._detail=this.register(this.detail);
		this.break1.add(this.detail);
		StringControl _C12=new StringControl();
		_C12.setPicture("@K#####|-####KB").setAt(4771,63,null,null);
		this._cusZipcode=this.register(_C12.use(Main.customers.zipcode));
		this.detail.add(_C12);
		StringControl _C13=new StringControl();
		_C13.setPicture("@s35").setAt(42,63,1917,167);
		this._glotCustname=this.register(_C13.use(Main.glotCustname));
		this.detail.add(_C13);
		StringControl _C14=new StringControl();
		_C14.setPicture("@P<<<#PB").setAt(6688,63,438,167).setRight(null);
		this._cusExtension=this.register(_C14.use(Main.customers.extension));
		this.detail.add(_C14);
		StringControl _C15=new StringControl();
		_C15.setPicture("@s25").setAt(3271,63,1375,167);
		this._cusCity=this.register(_C15.use(Main.customers.city));
		this.detail.add(_C15);
		StringControl _C16=new StringControl();
		_C16.setPicture("@s20").setAt(2052,63,1115,167);
		this._cusCompany=this.register(_C16.use(Main.customers.company));
		this.detail.add(_C16);
		StringControl _C17=new StringControl();
		_C17.setPicture("@P(###) ###-####PB").setAt(5729,63,906,167);
		this._cusPhonenumber=this.register(_C17.use(Main.customers.phonenumber));
		this.detail.add(_C17);
		ReportFooter _C18=new ReportFooter();
		_C18.setAt(469,10260,7521,271);
		this.add(_C18);
		StringControl _C19=new StringControl();
		_C19.setPageNo().setPicture("@pPage <<<#p").setAt(6688,42,729,188).setFont("MS Serif",10,null,Font.REGULAR,null);
		this._pagecount=this.register(_C19);
		_C18.add(_C19);
	}
}
