  MODULE('INVOI001.CLW')
SelectStates           PROCEDURE                      !Browse the States File and Edit-in-Place update
UpdateCustomers        PROCEDURE                      !Update the Customers File
BrowseAllOrders        PROCEDURE                      !Browse Orders using a relation tree
SelectProducts         PROCEDURE                      !Select a Products Record
UpdateDetail           PROCEDURE                      !Update the Detail File
UpdateOrders           PROCEDURE                      !Update the Orders File
  END
