  MODULE('INVOI003.CLW')
UpdateProducts         PROCEDURE                      !Update the Products File
PrintCUS:StateKey      PROCEDURE                      !Report the Customers File
PrintPRO:KeyProductSKU PROCEDURE                      !Report the Products File
PrintInvoice           PROCEDURE                      !Prints Invoice - Using the Pause Control Template
PrintMailingLabels     PROCEDURE                      !Printing mailing labels
SplashScreen           PROCEDURE
  END
