
  OMIT('EndDefine',_IBLOB_)
_IBLOB_  EQUATE(1)

!**********************************************************************
!
! Module:     iblob.inc
!
! Author:     Andrew Ireland
!
! Purpose:    Blob Interchange Interfaces
!
! Copyright 1998 Topspeed Corporation
!
!**********************************************************************

!**********************************************************************
!
! Revision Record
!
! Rev   Date      Author        Details
! ===================================================================
! 1.0   19/02/99  AI            Initial Creation
!
!**********************************************************************

!*
!*  Includes
!*

!*
!*  Equates
!*

!*
!*  Definitions
!*

!*
!*  Function Prototypes
!*

  MAP
  END

!**********************************************************************
!
! Interface:  IBlobCreate
!
! Purpose:
!
!**********************************************************************

IBlobCreate         INTERFACE
                    END

!**********************************************************************
!
! Interface:  IBlobRead
!
! Purpose:
!
!**********************************************************************

IBlobRead           INTERFACE
                    END

!**********************************************************************
!
! Interface:  IBlobSearch
!
! Purpose:
!
!**********************************************************************

IBlobSearch         INTERFACE
                    END


  EndDefine

