  MODULE('INVOI001.CLW')
SelectStates           PROCEDURE                      !Browse the States File and Edit-in-Place update
UpdateCustomers        PROCEDURE                      !Update the Customers File
BrowseAllOrders        PROCEDURE                      !Browse Orders using a relation tree
SelectProducts         PROCEDURE                      !Select a Products Record
UpdateDetail           PROCEDURE                      !Update the Detail File
UpdateOrders           PROCEDURE                      !Update the Orders File
PrintInvoiceFromBrowse PROCEDURE                      !Prints Invoice for each order
BrowseOrders           PROCEDURE                      !Browse the Orders File
BrowseCustomers        PROCEDURE                      !Browse the Customers File with "Filter Locator"
  END
