package clarion.winla001;

import clarion.equates.Font;
import clarion.equates.Std;
import org.jclarion.clarion.ClarionApplication;
import org.jclarion.clarion.control.ButtonControl;
import org.jclarion.clarion.control.ItemControl;
import org.jclarion.clarion.control.MenuControl;
import org.jclarion.clarion.control.MenubarControl;
import org.jclarion.clarion.control.SeparatorControl;
import org.jclarion.clarion.control.ToolbarControl;

@SuppressWarnings("all")
public class Appframe extends ClarionApplication
{
	public int _seanss=0;
	public int _printsetup=0;
	public int _exit=0;
	public int _seanssparmani=0;
	public int _oneseanss4ftp=0;
	public int _serviss=0;
	public int _servisskalkulators=0;
	public int _system=0;
	public int _systemglob=0;
	public int _systemparoles=0;
	public int _faili=0;
	public int _browsekon_k=0;
	public int _browsebankas_k=0;
	public int _browseval_k=0;
	public int _browsekursi_k=0;
	public int _fourfaili6nodalas=0;
	public int _failiprojekti=0;
	public int _failiatzimespartneriem=0;
	public int _failiizzinasnofailiem2=0;
	public int _fourfaili9izzinasnofailiem1partnerusaraksts=0;
	public int _izzinasnofailiemkontuplans=0;
	public int _fourfaili9izzinasnofailiem2bankusarakstsplans=0;
	public int _failiizzinasnofailiematlaizulapas=0;
	public int _failiizzinasnofailiempieskirtasatlaides=0;
	public int _fourfaili9izzinasnofailiem6atlaidesklientiem=0;
	public int _fourfailizizz7atzpartneriem=0;
	public int _tbarbrwtop=0;
	public int _tbarbrwpageup=0;
	public int _tbarbrwup=0;
	public int _tbarbrwlocate=0;
	public int _tbarbrwdown=0;
	public int _tbarbrwpagedown=0;
	public int _tbarbrwbottom=0;
	public int _tbarbrwselect=0;
	public int _tbarbrwinsert=0;
	public int _tbarbrwchange=0;
	public int _tbarbrwdelete=0;
	public int _tbarbrwhistory=0;
	public int _tbarbrwhelp=0;
	public Appframe()
	{
		this.setText(" ").setAt(null,null,453,325).setFont("MS Sans Serif",9,null,Font.BOLD,null).setIcon("CLARION.ICO").setSystem().setMax().setMaximize().setResize().setImmediate();
		this.setId("main.appframe");
		MenubarControl _C1=new MenubarControl();
		this.add(_C1);
		MenuControl _C2=new MenuControl();
		_C2.setText("&1-Seanss");
		this._seanss=this.register(_C2,"main.appframe.seanss");
		_C1.add(_C2);
		ItemControl _C3=new ItemControl();
		_C3.setText("&1-Printera parametri").setMsg("Windows printera parametri").setStandard(Std.PRINTSETUP);
		this._printsetup=this.register(_C3,"main.appframe.printsetup");
		_C2.add(_C3);
		SeparatorControl _C4=new SeparatorControl();
		_C2.add(_C4);
		ItemControl _C5=new ItemControl();
		_C5.setText("&2-Beigt darbu").setMsg("Beigt darbu ar �o aplik�ciju").setStandard(Std.CLOSE);
		this._exit=this.register(_C5,"main.appframe.exit");
		_C2.add(_C5);
		ItemControl _C6=new ItemControl();
		_C6.setText("&3-ParMani").setHidden().setMsg("Par mani");
		this._seanssparmani=this.register(_C6,"main.appframe.seanssparmani");
		_C2.add(_C6);
		ItemControl _C7=new ItemControl();
		_C7.setText("&4-FTP:WinLats lejuplde no www.assako.lv").setHidden();
		this._oneseanss4ftp=this.register(_C7,"main.appframe.oneseanss4ftp");
		_C2.add(_C7);
		MenuControl _C8=new MenuControl();
		_C8.setText("&2-Serviss");
		this._serviss=this.register(_C8,"main.appframe.serviss");
		_C1.add(_C8);
		ItemControl _C9=new ItemControl();
		_C9.setText("&1-Kalkul�tors").setMsg("Kalkul�tors");
		this._servisskalkulators=this.register(_C9,"main.appframe.servisskalkulators");
		_C8.add(_C9);
		MenuControl _C10=new MenuControl();
		_C10.setText("&3-Sist�mas dati");
		this._system=this.register(_C10,"main.appframe.system");
		_C1.add(_C10);
		ItemControl _C11=new ItemControl();
		_C11.setText("&1-Glob�lie dati").setDisabled().setMsg("Konkr�t� gada datub�zes Glob�lie dati");
		this._systemglob=this.register(_C11,"main.appframe.systemglob");
		_C10.add(_C11);
		ItemControl _C12=new ItemControl();
		_C12.setText("&2-Paroles").setDisabled().setMsg("Paroles, tikai DB adminstratora pieeja");
		this._systemparoles=this.register(_C12,"main.appframe.systemparoles");
		_C10.add(_C12);
		MenuControl _C13=new MenuControl();
		_C13.setText("&4-Faili");
		this._faili=this.register(_C13,"main.appframe.faili");
		_C1.add(_C13);
		ItemControl _C14=new ItemControl();
		_C14.setText("&2-Kontu pl�ns").setMsg("Browse KON_K");
		this._browsekon_k=this.register(_C14,"main.appframe.browsekon_k");
		_C13.add(_C14);
		ItemControl _C15=new ItemControl();
		_C15.setText("&3-Banku saraksts").setMsg("Browse BANKAS_K");
		this._browsebankas_k=this.register(_C15,"main.appframe.browsebankas_k");
		_C13.add(_C15);
		ItemControl _C16=new ItemControl();
		_C16.setText("&4-Val�tas un valstis").setMsg("Browse VAL_K");
		this._browseval_k=this.register(_C16,"main.appframe.browseval_k");
		_C13.add(_C16);
		ItemControl _C17=new ItemControl();
		_C17.setText("&5-Val�tu kursi").setMsg("Browse KURSI_K");
		this._browsekursi_k=this.register(_C17,"main.appframe.browsekursi_k");
		_C13.add(_C17);
		ItemControl _C18=new ItemControl();
		_C18.setText("&6-Noda�as");
		this._fourfaili6nodalas=this.register(_C18,"main.appframe.fourfaili6nodalas");
		_C13.add(_C18);
		ItemControl _C19=new ItemControl();
		_C19.setText("&7-Projekti");
		this._failiprojekti=this.register(_C19,"main.appframe.failiprojekti");
		_C13.add(_C19);
		ItemControl _C20=new ItemControl();
		_C20.setText("&8-Atz�mes Partneriem");
		this._failiatzimespartneriem=this.register(_C20,"main.appframe.failiatzimespartneriem");
		_C13.add(_C20);
		SeparatorControl _C21=new SeparatorControl();
		_C13.add(_C21);
		MenuControl _C22=new MenuControl();
		_C22.setText("&Z-Izzi�as no failiem");
		this._failiizzinasnofailiem2=this.register(_C22,"main.appframe.failiizzinasnofailiem2");
		_C13.add(_C22);
		ItemControl _C23=new ItemControl();
		_C23.setText("&1-Partneru saraksts");
		this._fourfaili9izzinasnofailiem1partnerusaraksts=this.register(_C23,"main.appframe.fourfaili9izzinasnofailiem1partnerusaraksts");
		_C22.add(_C23);
		ItemControl _C24=new ItemControl();
		_C24.setText("&2-Kontu pl�ns");
		this._izzinasnofailiemkontuplans=this.register(_C24,"main.appframe.izzinasnofailiemkontuplans");
		_C22.add(_C24);
		ItemControl _C25=new ItemControl();
		_C25.setText("&3-Banku saraksts");
		this._fourfaili9izzinasnofailiem2bankusarakstsplans=this.register(_C25,"main.appframe.fourfaili9izzinasnofailiem2bankusarakstsplans");
		_C22.add(_C25);
		ItemControl _C26=new ItemControl();
		_C26.setText("&4-Atlai�u lapas");
		this._failiizzinasnofailiematlaizulapas=this.register(_C26,"main.appframe.failiizzinasnofailiematlaizulapas");
		_C22.add(_C26);
		ItemControl _C27=new ItemControl();
		_C27.setText("&5-Pie��irt�s atlaides");
		this._failiizzinasnofailiempieskirtasatlaides=this.register(_C27,"main.appframe.failiizzinasnofailiempieskirtasatlaides");
		_C22.add(_C27);
		ItemControl _C28=new ItemControl();
		_C28.setText("&6-Atlaides klientiem");
		this._fourfaili9izzinasnofailiem6atlaidesklientiem=this.register(_C28,"main.appframe.fourfaili9izzinasnofailiem6atlaidesklientiem");
		_C22.add(_C28);
		ItemControl _C29=new ItemControl();
		_C29.setText("&7-Atz�mes partneriem");
		this._fourfailizizz7atzpartneriem=this.register(_C29,"main.appframe.fourfailizizz7atzpartneriem");
		_C22.add(_C29);
		ToolbarControl _C30=new ToolbarControl();
		_C30.setAt(0,0,453,18).setFont(null,9,null,Font.BOLD,null);
		this.add(_C30);
		ButtonControl _C31=new ButtonControl();
		_C31.setIcon("VCRFIRST.ICO").setAt(4,2,16,14).setDisabled().setTip("Uz Pirmo lapu");
		this._tbarbrwtop=this.register(_C31,"main.appframe.tbarbrwtop");
		_C30.add(_C31);
		ButtonControl _C32=new ButtonControl();
		_C32.setIcon("VCRPRIOR.ICO").setAt(20,2,16,14).setDisabled().setTip("Go to the Prior Page");
		this._tbarbrwpageup=this.register(_C32,"main.appframe.tbarbrwpageup");
		_C30.add(_C32);
		ButtonControl _C33=new ButtonControl();
		_C33.setIcon("VCRUP.ICO").setAt(36,2,16,14).setDisabled().setTip("Go to the Prior Record");
		this._tbarbrwup=this.register(_C33,"main.appframe.tbarbrwup");
		_C30.add(_C33);
		ButtonControl _C34=new ButtonControl();
		_C34.setIcon("FIND.ICO").setAt(52,2,16,14).setDisabled().setTip("Locate record");
		this._tbarbrwlocate=this.register(_C34,"main.appframe.tbarbrwlocate");
		_C30.add(_C34);
		ButtonControl _C35=new ButtonControl();
		_C35.setIcon("VCRDOWN.ICO").setAt(68,2,16,14).setDisabled().setTip("Go to the Next Record");
		this._tbarbrwdown=this.register(_C35,"main.appframe.tbarbrwdown");
		_C30.add(_C35);
		ButtonControl _C36=new ButtonControl();
		_C36.setIcon("VCRNEXT.ICO").setAt(84,2,16,14).setDisabled().setTip("Go to the Next Page");
		this._tbarbrwpagedown=this.register(_C36,"main.appframe.tbarbrwpagedown");
		_C30.add(_C36);
		ButtonControl _C37=new ButtonControl();
		_C37.setIcon("VCRLAST.ICO").setAt(100,2,16,14).setDisabled().setTip("Go to the Last Page");
		this._tbarbrwbottom=this.register(_C37,"main.appframe.tbarbrwbottom");
		_C30.add(_C37);
		ButtonControl _C38=new ButtonControl();
		_C38.setIcon("MARK.ICO").setAt(120,2,16,14).setDisabled().setTip("Select This Record");
		this._tbarbrwselect=this.register(_C38,"main.appframe.tbarbrwselect");
		_C30.add(_C38);
		ButtonControl _C39=new ButtonControl();
		_C39.setIcon("INSERT.ICO").setAt(136,2,16,14).setDisabled().setTip("Insert a New Record");
		this._tbarbrwinsert=this.register(_C39,"main.appframe.tbarbrwinsert");
		_C30.add(_C39);
		ButtonControl _C40=new ButtonControl();
		_C40.setIcon("EDIT.ICO").setAt(152,2,16,14).setDisabled().setTip("Edit This Record");
		this._tbarbrwchange=this.register(_C40,"main.appframe.tbarbrwchange");
		_C30.add(_C40);
		ButtonControl _C41=new ButtonControl();
		_C41.setIcon("DELETE.ICO").setAt(168,2,16,14).setDisabled().setTip("Delete This Record");
		this._tbarbrwdelete=this.register(_C41,"main.appframe.tbarbrwdelete");
		_C30.add(_C41);
		ButtonControl _C42=new ButtonControl();
		_C42.setIcon("DITTO.ICO").setAt(188,2,16,14).setDisabled().setTip("Previous value");
		this._tbarbrwhistory=this.register(_C42,"main.appframe.tbarbrwhistory");
		_C30.add(_C42);
		ButtonControl _C43=new ButtonControl();
		_C43.setIcon("HELP.ICO").setAt(204,2,16,14).setDisabled().setTip("Get Help");
		this._tbarbrwhelp=this.register(_C43,"main.appframe.tbarbrwhelp");
		_C30.add(_C43);
	}
}
