
  omit('EndDefine',_WINERR_)
_WINERR_  equate(1)

ERROR_SUCCESS           equate(0)
NO_ERROR                equate(0)

ERROR_MORE_DATA         equate(234)
ERROR_NO_MORE_ITEMS     equate(259)

REGDB_E_CLASSNOTREG     equate(080040154h)
REGDB_E_READREGDB       equate(080040150h)
CO_E_DLLNOTFOUND        equate(0800401F8h)
CO_E_APPNOTFOUND        equate(0800401F5h)
CO_E_ERRORINDLL         equate(0800401F9h)
CO_E_APPDIDNTREG        equate(0800401FEh)

  EndDefine

