package clarion;

import clarion.Main;
import clarion.equates.Color;
import clarion.equates.Icon;
import clarion.equates.Std;
import org.jclarion.clarion.ClarionWindow;
import org.jclarion.clarion.control.ButtonControl;
import org.jclarion.clarion.control.CheckControl;
import org.jclarion.clarion.control.EntryControl;
import org.jclarion.clarion.control.PromptControl;
import org.jclarion.clarion.control.SheetControl;
import org.jclarion.clarion.control.StringControl;
import org.jclarion.clarion.control.TabControl;

public class QuickWindow_4 extends ClarionWindow
{
	public int _currentTab=0;
	public int _tab1=0;
	public int _oRDOrderDatePrompt=0;
	public int _oRDOrderDate=0;
	public int _oRDInvoiceNumberPrompt=0;
	public int _oRDInvoiceNumber=0;
	public int _oRDSameName=0;
	public int _oRDShipToNamePrompt=0;
	public int _oRDShipToName=0;
	public int _oRDSameAdd=0;
	public int _oRDShipAddress1Prompt=0;
	public int _oRDShipAddress1=0;
	public int _oRDShipAddress2Prompt=0;
	public int _oRDShipAddress2=0;
	public int _oRDShipCityPrompt=0;
	public int _oRDShipCity=0;
	public int _oRDShipStatePrompt=0;
	public int _oRDShipState=0;
	public int _oRDShipZipPrompt=0;
	public int _oRDShipZip=0;
	public int _oRDOrderShipped=0;
	public int _oRDOrderNotePrompt=0;
	public int _oRDOrderNote=0;
	public int _ok=0;
	public int _help=0;
	public int _cancel=0;
	public QuickWindow_4()
	{
		this.setText("Update Order").setAt(null,null,275,163).setFont("MS Sans Serif",8,Color.BLACK,null,null).setCenter().setImmediate().setIcon("NOTE14.ICO").setHelp("~UpdateOrder").setSystem().setGray().setResize().setMDI();
		this.setId("updateorders.quickwindow");
		SheetControl _C1=new SheetControl();
		_C1.setWizard().setAt(3,2,269,159);
		this._currentTab=this.register(_C1,"updateorders.quickwindow.currenttab");
		this.add(_C1);
		TabControl _C2=new TabControl();
		_C2.setText("Tab 1");
		this._tab1=this.register(_C2,"updateorders.quickwindow.tab1");
		_C1.add(_C2);
		PromptControl _C3=new PromptControl();
		_C3.setText("Order Date:").setAt(8,7,null,null);
		this._oRDOrderDatePrompt=this.register(_C3,"updateorders.quickwindow.ord:orderdate:prompt");
		this.add(_C3);
		StringControl _C4=new StringControl();
		_C4.setPicture("@d1").setAt(63,7,41,10);
		this._oRDOrderDate=this.register(_C4.use(Main.orders.orderDate),"updateorders.quickwindow.ord:orderdate");
		this.add(_C4);
		PromptControl _C5=new PromptControl();
		_C5.setText("Invoice Number:").setAt(131,7,57,10);
		this._oRDInvoiceNumberPrompt=this.register(_C5,"updateorders.quickwindow.ord:invoicenumber:prompt");
		this.add(_C5);
		StringControl _C6=new StringControl();
		_C6.setPicture("@n07").setAt(197,7,null,null);
		this._oRDInvoiceNumber=this.register(_C6.use(Main.orders.invoiceNumber),"updateorders.quickwindow.ord:invoicenumber");
		this.add(_C6);
		CheckControl _C7=new CheckControl();
		_C7.setText("Same Name As Customer's").setAt(63,18,113,10).setMsg("ShipTo name same as Customer's");
		this._oRDSameName=this.register(_C7.use(Main.orders.sameName),"updateorders.quickwindow.ord:samename");
		this.add(_C7);
		PromptControl _C8=new PromptControl();
		_C8.setText("Ship To Name:").setAt(8,31,null,null);
		this._oRDShipToNamePrompt=this.register(_C8,"updateorders.quickwindow.ord:shiptoname:prompt");
		this.add(_C8);
		EntryControl _C9=new EntryControl();
		_C9.setCapitalise().setPicture("@s45").setAt(63,31,176,10).setMsg("Customer the order is shipped to");
		this._oRDShipToName=this.register(_C9.use(Main.orders.shipToName),"updateorders.quickwindow.ord:shiptoname");
		this.add(_C9);
		CheckControl _C10=new CheckControl();
		_C10.setText("Same  Address As Customer's").setAt(63,44,113,10).setMsg("Ship to address same as customer's");
		this._oRDSameAdd=this.register(_C10.use(Main.orders.sameAdd),"updateorders.quickwindow.ord:sameadd");
		this.add(_C10);
		PromptControl _C11=new PromptControl();
		_C11.setText("Ship Address 1:").setAt(8,58,null,null);
		this._oRDShipAddress1Prompt=this.register(_C11,"updateorders.quickwindow.ord:shipaddress1:prompt");
		this.add(_C11);
		EntryControl _C12=new EntryControl();
		_C12.setCapitalise().setPicture("@s35").setAt(63,58,144,10).setMsg("1st Line of ship address");
		this._oRDShipAddress1=this.register(_C12.use(Main.orders.shipAddress1),"updateorders.quickwindow.ord:shipaddress1");
		this.add(_C12);
		PromptControl _C13=new PromptControl();
		_C13.setText("Ship Address 2:").setAt(8,71,null,null);
		this._oRDShipAddress2Prompt=this.register(_C13,"updateorders.quickwindow.ord:shipaddress2:prompt");
		this.add(_C13);
		EntryControl _C14=new EntryControl();
		_C14.setCapitalise().setPicture("@s35").setAt(63,73,144,10).setMsg("2nd line of ship address");
		this._oRDShipAddress2=this.register(_C14.use(Main.orders.shipAddress2),"updateorders.quickwindow.ord:shipaddress2");
		this.add(_C14);
		PromptControl _C15=new PromptControl();
		_C15.setText("Ship City:").setAt(8,87,null,null);
		this._oRDShipCityPrompt=this.register(_C15,"updateorders.quickwindow.ord:shipcity:prompt");
		this.add(_C15);
		EntryControl _C16=new EntryControl();
		_C16.setCapitalise().setPicture("@s25").setAt(63,87,104,10).setMsg("City of Ship address");
		this._oRDShipCity=this.register(_C16.use(Main.orders.shipCity),"updateorders.quickwindow.ord:shipcity");
		this.add(_C16);
		PromptControl _C17=new PromptControl();
		_C17.setText("Ship State:").setAt(8,103,null,null);
		this._oRDShipStatePrompt=this.register(_C17,"updateorders.quickwindow.ord:shipstate:prompt");
		this.add(_C17);
		EntryControl _C18=new EntryControl();
		_C18.setUpper().setPicture("@s2").setAt(63,103,25,10).setMsg("State to ship to");
		this._oRDShipState=this.register(_C18.use(Main.orders.shipState),"updateorders.quickwindow.ord:shipstate");
		this.add(_C18);
		PromptControl _C19=new PromptControl();
		_C19.setText("Ship Zip:").setAt(96,103,33,10);
		this._oRDShipZipPrompt=this.register(_C19,"updateorders.quickwindow.ord:shipzip:prompt");
		this.add(_C19);
		EntryControl _C20=new EntryControl();
		_C20.setPicture("@K#####|-####KB").setAt(131,103,60,10).setMsg("ZipCode of ship city");
		this._oRDShipZip=this.register(_C20.use(Main.orders.shipZip),"updateorders.quickwindow.ord:shipzip");
		this.add(_C20);
		CheckControl _C21=new CheckControl();
		_C21.setText("Order Shipped").setAt(205,103,59,10).setMsg("Checked if order is shipped");
		this._oRDOrderShipped=this.register(_C21.use(Main.orders.orderShipped),"updateorders.quickwindow.ord:ordershipped");
		this.add(_C21);
		PromptControl _C22=new PromptControl();
		_C22.setText("Order Note:").setAt(8,119,null,null);
		this._oRDOrderNotePrompt=this.register(_C22,"updateorders.quickwindow.ord:ordernote:prompt");
		this.add(_C22);
		EntryControl _C23=new EntryControl();
		_C23.setPicture("@s80").setAt(63,119,204,10).setMsg("Additional Information about order");
		this._oRDOrderNote=this.register(_C23.use(Main.orders.orderNote),"updateorders.quickwindow.ord:ordernote");
		this.add(_C23);
		ButtonControl _C24=new ButtonControl();
		_C24.setFlat().setIcon("DISK12.ICO").setDefault().setAt(99,137,20,19).setLeft(null).setMsg("Save  record and Exit").setTip("Save  record and Exit");
		this._ok=this.register(_C24,"updateorders.quickwindow.ok");
		this.add(_C24);
		ButtonControl _C25=new ButtonControl();
		_C25.setFlat().setIcon(Icon.HELP).setAt(133,139,13,14).setHidden().setTip("Get Help").setStandard(Std.HELP);
		this._help=this.register(_C25,"updateorders.quickwindow.help");
		this.add(_C25);
		ButtonControl _C26=new ButtonControl();
		_C26.setFlat().setIcon(Icon.CROSS).setAt(159,137,20,19).setMsg("Cancel changes and Exit").setTip("Cancel changes and Exit");
		this._cancel=this.register(_C26,"updateorders.quickwindow.cancel");
		this.add(_C26);
	}
}
