package clarion;

import clarion.Main;
import clarion.equates.Color;
import clarion.equates.Font;
import clarion.equates.Icon;
import clarion.equates.Std;
import org.jclarion.clarion.ClarionWindow;
import org.jclarion.clarion.control.ButtonControl;
import org.jclarion.clarion.control.EntryControl;
import org.jclarion.clarion.control.GroupControl;
import org.jclarion.clarion.control.ImageControl;
import org.jclarion.clarion.control.PromptControl;
import org.jclarion.clarion.control.SheetControl;
import org.jclarion.clarion.control.TabControl;

public class QuickWindow_5 extends ClarionWindow
{
	public int _currentTab=0;
	public int _tab1=0;
	public int _pROProductSKUPrompt=0;
	public int _pROProductSKU=0;
	public int _pRODescriptionPrompt=0;
	public int _pRODescription=0;
	public int _pROPricePrompt=0;
	public int _pROPrice=0;
	public int _pROCostPrompt=0;
	public int _pROCost=0;
	public int _pROQuantityInStock=0;
	public int _pROQuantityInStockPrompt=0;
	public int _pROReorderQuantityPrompt=0;
	public int _pROReorderQuantity=0;
	public int _pROPictureFilePrompt=0;
	public int _pROPictureFile=0;
	public int _lookupFile=0;
	public int _group1=0;
	public int _image1=0;
	public int _ok=0;
	public int _help=0;
	public int _cancel=0;
	public QuickWindow_5()
	{
		this.setText("Update Products").setAt(null,null,288,130).setFont("MS Sans Serif",8,Color.BLACK,null,null).setCenter().setImmediate().setIcon("FLOW04.ICO").setHelp("~UpdateProducts").setSystem().setGray().setDouble().setMDI();
		this.setId("updateproducts.quickwindow");
		SheetControl _C1=new SheetControl();
		_C1.setWizard().setAt(3,0,282,128);
		this._currentTab=this.register(_C1,"updateproducts.quickwindow.currenttab");
		this.add(_C1);
		TabControl _C2=new TabControl();
		_C2.setText("Tab 1");
		this._tab1=this.register(_C2,"updateproducts.quickwindow.tab1");
		_C1.add(_C2);
		PromptControl _C3=new PromptControl();
		_C3.setText("Product SKU:").setAt(7,9,null,null);
		this._pROProductSKUPrompt=this.register(_C3,"updateproducts.quickwindow.pro:productsku:prompt");
		this.add(_C3);
		EntryControl _C4=new EntryControl();
		_C4.setRequired().setUpper().setPicture("@s10").setAt(70,9,44,10).setLeft(1).setMsg("User defined Product Number");
		this._pROProductSKU=this.register(_C4.use(Main.products.productSKU),"updateproducts.quickwindow.pro:productsku");
		this.add(_C4);
		PromptControl _C5=new PromptControl();
		_C5.setText("Description:").setAt(7,25,null,null);
		this._pRODescriptionPrompt=this.register(_C5,"updateproducts.quickwindow.pro:description:prompt");
		this.add(_C5);
		EntryControl _C6=new EntryControl();
		_C6.setRequired().setCapitalise().setPicture("@s35").setAt(70,25,101,10).setLeft(1).setMsg("Enter Product's Description");
		this._pRODescription=this.register(_C6.use(Main.products.description),"updateproducts.quickwindow.pro:description");
		this.add(_C6);
		PromptControl _C7=new PromptControl();
		_C7.setText("Price:").setAt(7,41,29,10);
		this._pROPricePrompt=this.register(_C7,"updateproducts.quickwindow.pro:price:prompt");
		this.add(_C7);
		EntryControl _C8=new EntryControl();
		_C8.setPicture("@n$10.2B").setAt(70,41,35,10).setDecimal(12).setMsg("Enter Product's Price");
		this._pROPrice=this.register(_C8.use(Main.products.price),"updateproducts.quickwindow.pro:price");
		this.add(_C8);
		PromptControl _C9=new PromptControl();
		_C9.setText("Cost:").setAt(7,57,23,10);
		this._pROCostPrompt=this.register(_C9,"updateproducts.quickwindow.pro:cost:prompt");
		this.add(_C9);
		EntryControl _C10=new EntryControl();
		_C10.setPicture("@n$10.2B").setAt(70,57,35,10).setDecimal(12).setMsg("Enter product's cost");
		this._pROCost=this.register(_C10.use(Main.products.cost),"updateproducts.quickwindow.pro:cost");
		this.add(_C10);
		EntryControl _C11=new EntryControl();
		_C11.setPicture("@n-10.2").setAt(70,73,35,10).setDecimal(12).setMsg("Enter quantity of product in stock");
		this._pROQuantityInStock=this.register(_C11.use(Main.products.quantityInStock),"updateproducts.quickwindow.pro:quantityinstock");
		this.add(_C11);
		PromptControl _C12=new PromptControl();
		_C12.setText("Quantity In Stock:").setAt(7,73,60,10);
		this._pROQuantityInStockPrompt=this.register(_C12,"updateproducts.quickwindow.pro:quantityinstock:prompt");
		this.add(_C12);
		PromptControl _C13=new PromptControl();
		_C13.setText("Reorder Quantity:").setAt(7,89,59,10);
		this._pROReorderQuantityPrompt=this.register(_C13,"updateproducts.quickwindow.pro:reorderquantity:prompt");
		this.add(_C13);
		EntryControl _C14=new EntryControl();
		_C14.setPicture("@n9.2").setAt(70,89,35,10).setDecimal(12).setMsg("Enter product's quantity for re-order");
		this._pROReorderQuantity=this.register(_C14.use(Main.products.reorderQuantity),"updateproducts.quickwindow.pro:reorderquantity");
		this.add(_C14);
		PromptControl _C15=new PromptControl();
		_C15.setText("Picture File:").setAt(7,105,null,null);
		this._pROPictureFilePrompt=this.register(_C15,"updateproducts.quickwindow.pro:picturefile:prompt");
		this.add(_C15);
		EntryControl _C16=new EntryControl();
		_C16.setPicture("@s64").setAt(70,105,101,10).setDisabled().setLeft(1).setMsg("Path of graphic file");
		this._pROPictureFile=this.register(_C16.use(Main.products.pictureFile),"updateproducts.quickwindow.pro:picturefile");
		this.add(_C16);
		ButtonControl _C17=new ButtonControl();
		_C17.setIcon(Icon.NONE).setText("Select Image").setAt(110,87,65,14).setFont(null,null,Color.NAVY,Font.BOLD,null).setTip("Insert or Change Image");
		this._lookupFile=this.register(_C17,"updateproducts.quickwindow.lookupfile");
		this.add(_C17);
		GroupControl _C18=new GroupControl();
		_C18.setAt(181,5,97,94).setBoxed().setBevel(-2,2,null);
		this._group1=this.register(_C18,"updateproducts.quickwindow.group1");
		this.add(_C18);
		ImageControl _C19=new ImageControl();
		_C19.setAt(185,9,89,87);
		this._image1=this.register(_C19,"updateproducts.quickwindow.image1");
		_C18.add(_C19);
		ButtonControl _C20=new ButtonControl();
		_C20.setFlat().setIcon("DISK12.ICO").setDefault().setAt(195,105,22,20).setTip("Save record and exit ");
		this._ok=this.register(_C20,"updateproducts.quickwindow.ok");
		this.add(_C20);
		ButtonControl _C21=new ButtonControl();
		_C21.setFlat().setIcon(Icon.HELP).setAt(225,110,13,12).setHidden().setStandard(Std.HELP);
		this._help=this.register(_C21,"updateproducts.quickwindow.help");
		this.add(_C21);
		ButtonControl _C22=new ButtonControl();
		_C22.setFlat().setIcon(Icon.CROSS).setAt(244,105,22,20).setTip("Cancel changes and exit");
		this._cancel=this.register(_C22,"updateproducts.quickwindow.cancel");
		this.add(_C22);
	}
}
