package clarion;

import clarion.equates.Create;
import clarion.equates.Prop;
import org.jclarion.clarion.Clarion;
import org.jclarion.clarion.ClarionGroup;
import org.jclarion.clarion.ClarionNumber;

public class Translatortypemappings extends ClarionGroup
{
	public ClarionNumber _anon_1=Clarion.newNumber(Create.BUTTON).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_2=Clarion.newNumber(Prop.TEXT).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_3=Clarion.newNumber(Create.BUTTON).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_4=Clarion.newNumber(Prop.MSG).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_5=Clarion.newNumber(Create.BUTTON).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_6=Clarion.newNumber(Prop.TOOLTIP).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_7=Clarion.newNumber(Create.CHECK).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_8=Clarion.newNumber(Prop.TEXT).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_9=Clarion.newNumber(Create.CHECK).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_10=Clarion.newNumber(Prop.MSG).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_11=Clarion.newNumber(Create.CHECK).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_12=Clarion.newNumber(Prop.TOOLTIP).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_13=Clarion.newNumber(Create.COMBO).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_14=Clarion.newNumber(Prop.MSG).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_15=Clarion.newNumber(Create.COMBO).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_16=Clarion.newNumber(Prop.TOOLTIP).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_17=Clarion.newNumber(Create.ENTRY).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_18=Clarion.newNumber(Prop.MSG).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_19=Clarion.newNumber(Create.ENTRY).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_20=Clarion.newNumber(Prop.TOOLTIP).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_21=Clarion.newNumber(Create.GROUP).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_22=Clarion.newNumber(Prop.TEXT).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_23=Clarion.newNumber(Create.GROUP).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_24=Clarion.newNumber(Prop.MSG).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_25=Clarion.newNumber(Create.GROUP).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_26=Clarion.newNumber(Prop.TOOLTIP).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_27=Clarion.newNumber(Create.LIST).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_28=Clarion.newNumber(Prop.MSG).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_29=Clarion.newNumber(Create.LIST).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_30=Clarion.newNumber(Prop.TOOLTIP).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_31=Clarion.newNumber(Create.OPTION).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_32=Clarion.newNumber(Prop.TEXT).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_33=Clarion.newNumber(Create.OPTION).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_34=Clarion.newNumber(Prop.MSG).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_35=Clarion.newNumber(Create.OPTION).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_36=Clarion.newNumber(Prop.TOOLTIP).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_37=Clarion.newNumber(Create.PROMPT).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_38=Clarion.newNumber(Prop.TEXT).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_39=Clarion.newNumber(Create.RADIO).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_40=Clarion.newNumber(Prop.TEXT).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_41=Clarion.newNumber(Create.RADIO).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_42=Clarion.newNumber(Prop.MSG).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_43=Clarion.newNumber(Create.RADIO).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_44=Clarion.newNumber(Prop.TOOLTIP).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_45=Clarion.newNumber(Create.SPIN).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_46=Clarion.newNumber(Prop.MSG).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_47=Clarion.newNumber(Create.SPIN).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_48=Clarion.newNumber(Prop.TOOLTIP).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_49=Clarion.newNumber(Create.STRING).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_50=Clarion.newNumber(Prop.TEXT).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_51=Clarion.newNumber(Create.SSTRING).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_52=Clarion.newNumber(Prop.TEXT).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_53=Clarion.newNumber(Create.TAB).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_54=Clarion.newNumber(Prop.TEXT).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_55=Clarion.newNumber(Create.TAB).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_56=Clarion.newNumber(Prop.MSG).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_57=Clarion.newNumber(Create.TAB).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_58=Clarion.newNumber(Prop.TOOLTIP).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_59=Clarion.newNumber(Create.TEXT).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_60=Clarion.newNumber(Prop.MSG).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_61=Clarion.newNumber(Create.TEXT).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_62=Clarion.newNumber(Prop.TOOLTIP).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_63=Clarion.newNumber(Create.MENU).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_64=Clarion.newNumber(Prop.TEXT).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_65=Clarion.newNumber(Create.MENU).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_66=Clarion.newNumber(Prop.MSG).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_67=Clarion.newNumber(Create.ITEM).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_68=Clarion.newNumber(Prop.TEXT).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_69=Clarion.newNumber(Create.ITEM).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_70=Clarion.newNumber(Prop.MSG).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_71=Clarion.newNumber(Create.RTF).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_72=Clarion.newNumber(Prop.MSG).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_73=Clarion.newNumber(Create.RTF).setEncoding(ClarionNumber.USHORT);
	public ClarionNumber _anon_74=Clarion.newNumber(Prop.TOOLTIP).setEncoding(ClarionNumber.USHORT);

	public Translatortypemappings()
	{
		this.addVariable("_anon_1",this._anon_1);
		this.addVariable("_anon_2",this._anon_2);
		this.addVariable("_anon_3",this._anon_3);
		this.addVariable("_anon_4",this._anon_4);
		this.addVariable("_anon_5",this._anon_5);
		this.addVariable("_anon_6",this._anon_6);
		this.addVariable("_anon_7",this._anon_7);
		this.addVariable("_anon_8",this._anon_8);
		this.addVariable("_anon_9",this._anon_9);
		this.addVariable("_anon_10",this._anon_10);
		this.addVariable("_anon_11",this._anon_11);
		this.addVariable("_anon_12",this._anon_12);
		this.addVariable("_anon_13",this._anon_13);
		this.addVariable("_anon_14",this._anon_14);
		this.addVariable("_anon_15",this._anon_15);
		this.addVariable("_anon_16",this._anon_16);
		this.addVariable("_anon_17",this._anon_17);
		this.addVariable("_anon_18",this._anon_18);
		this.addVariable("_anon_19",this._anon_19);
		this.addVariable("_anon_20",this._anon_20);
		this.addVariable("_anon_21",this._anon_21);
		this.addVariable("_anon_22",this._anon_22);
		this.addVariable("_anon_23",this._anon_23);
		this.addVariable("_anon_24",this._anon_24);
		this.addVariable("_anon_25",this._anon_25);
		this.addVariable("_anon_26",this._anon_26);
		this.addVariable("_anon_27",this._anon_27);
		this.addVariable("_anon_28",this._anon_28);
		this.addVariable("_anon_29",this._anon_29);
		this.addVariable("_anon_30",this._anon_30);
		this.addVariable("_anon_31",this._anon_31);
		this.addVariable("_anon_32",this._anon_32);
		this.addVariable("_anon_33",this._anon_33);
		this.addVariable("_anon_34",this._anon_34);
		this.addVariable("_anon_35",this._anon_35);
		this.addVariable("_anon_36",this._anon_36);
		this.addVariable("_anon_37",this._anon_37);
		this.addVariable("_anon_38",this._anon_38);
		this.addVariable("_anon_39",this._anon_39);
		this.addVariable("_anon_40",this._anon_40);
		this.addVariable("_anon_41",this._anon_41);
		this.addVariable("_anon_42",this._anon_42);
		this.addVariable("_anon_43",this._anon_43);
		this.addVariable("_anon_44",this._anon_44);
		this.addVariable("_anon_45",this._anon_45);
		this.addVariable("_anon_46",this._anon_46);
		this.addVariable("_anon_47",this._anon_47);
		this.addVariable("_anon_48",this._anon_48);
		this.addVariable("_anon_49",this._anon_49);
		this.addVariable("_anon_50",this._anon_50);
		this.addVariable("_anon_51",this._anon_51);
		this.addVariable("_anon_52",this._anon_52);
		this.addVariable("_anon_53",this._anon_53);
		this.addVariable("_anon_54",this._anon_54);
		this.addVariable("_anon_55",this._anon_55);
		this.addVariable("_anon_56",this._anon_56);
		this.addVariable("_anon_57",this._anon_57);
		this.addVariable("_anon_58",this._anon_58);
		this.addVariable("_anon_59",this._anon_59);
		this.addVariable("_anon_60",this._anon_60);
		this.addVariable("_anon_61",this._anon_61);
		this.addVariable("_anon_62",this._anon_62);
		this.addVariable("_anon_63",this._anon_63);
		this.addVariable("_anon_64",this._anon_64);
		this.addVariable("_anon_65",this._anon_65);
		this.addVariable("_anon_66",this._anon_66);
		this.addVariable("_anon_67",this._anon_67);
		this.addVariable("_anon_68",this._anon_68);
		this.addVariable("_anon_69",this._anon_69);
		this.addVariable("_anon_70",this._anon_70);
		this.addVariable("_anon_71",this._anon_71);
		this.addVariable("_anon_72",this._anon_72);
		this.addVariable("_anon_73",this._anon_73);
		this.addVariable("_anon_74",this._anon_74);
	}
}
