  MODULE('CARDR001.CLW')
AuthorInformation      PROCEDURE
UpdateAccounts         PROCEDURE                      !Update the Accounts File
BrowseAccounts         PROCEDURE                      !Browse the Credit Card Accounts File
PrintCreditCardRegistry PROCEDURE                     !Print Information on All Credit Card Accounts
UpdateTransactions     PROCEDURE                      !Update the Transactions File
BrowseCurrentTransactions PROCEDURE                   !Browse Reconciled Transactions 
BrowseTransactionHistory PROCEDURE                    !Browse Reconciled Transactions 
PrintAccountPurchases  PROCEDURE                      !Print Charge History for an Account
PickaReport            PROCEDURE                      !Pick A Report
  END
