! Used to test all 32 permutations of the GROUP keyword

! 1
Window WINDOW
	group
	END
END

! 2
Window WINDOW
	grouP
	END
END

! 3
Window WINDOW
	groUp
	END
END

! 4
Window WINDOW
	groUP
	END
END

! 5
Window WINDOW
	grOup
	END
END

! 6
Window WINDOW
	grOuP
	END
END

! 7
Window WINDOW
	grOUp
	END
END

! 8
Window WINDOW
	grOUP
	END
END

! 9
Window WINDOW
	gRoup
	END
END

! 10
Window WINDOW
	gRouP
	END
END

! 11
Window WINDOW
	gRoUp
	END
END

! 12
Window WINDOW
	gRoUP
	END
END

! 13
Window WINDOW
	gROup
	END
END

! 14
Window WINDOW
	gROuP
	END
END

! 15
Window WINDOW
	gROUp
	END
END

! 16
Window WINDOW
	gROUP
	END
END

! 17
Window WINDOW
	Group
	END
END

! 18
Window WINDOW
	GrouP
	END
END

! 19
Window WINDOW
	GroUp
	END
END

! 20
Window WINDOW
	GroUP
	END
END

! 21
Window WINDOW
	GrOup
	END
END

! 22
Window WINDOW
	GrOuP
	END
END

! 23
Window WINDOW
	GrOUp
	END
END

! 24
Window WINDOW
	GrOUP
	END
END

! 25
Window WINDOW
	GRoup
	END
END

! 26
Window WINDOW
	GRouP
	END
END

! 27
Window WINDOW
	GRoUp
	END
END

! 28
Window WINDOW
	GRoUP
	END
END

! 29
Window WINDOW
	GROup
	END
END

! 30
Window WINDOW
	GROuP
	END
END

! 31
Window WINDOW
	GROUp
	END
END

! 32
Window WINDOW
	GROUP
	END
END