! Used to test all 64 permutations of the WINDOW keyword

! 1
Window window
END

! 2
Window windoW
END

! 3
Window windOw
END

! 4
Window windOW
END

! 5
Window winDow
END

! 6
Window winDoW
END

! 7
Window winDOw
END

! 8
Window winDOW
END

! 9
Window wiNdow
END

! 10
Window wiNdoW
END

! 11
Window wiNdOw
END

! 12
Window wiNdOW
END

! 13
Window wiNDow
END

! 14
Window wiNDoW
END

! 15
Window wiNDOw
END

! 16
Window wiNDOW
END

! 17
Window wIndow
END

! 18
Window wIndoW
END

! 19
Window wIndOw
END

! 20
Window wIndOW
END

! 21
Window wInDow
END

! 22
Window wInDoW
END

! 23
Window wInDOw
END

! 24
Window wInDOW
END

! 25
Window wINdow
END

! 26
Window wINdoW
END

! 27
Window wINdOw
END

! 28
Window wINdOW
END

! 29
Window wINDow
END

! 30
Window wINDoW
END

! 31
Window wINDOw
END

! 32
Window wINDOW
END

! 33
Window WindoW
END

! 34
Window WindoW
END

! 35
Window WindOW
END

! 36
Window WindOW
END

! 37
Window WinDoW
END

! 38
Window WinDoW
END

! 39
Window WinDOW
END

! 40
Window WinDOW
END

! 41
Window WiNdoW
END

! 42
Window WiNdoW
END

! 43
Window WiNdOW
END

! 44
Window WiNdOW
END

! 45
Window WiNDoW
END

! 46
Window WiNDoW
END

! 47
Window WiNDOW
END

! 48
Window WiNDOW
END

! 49
Window WIndoW
END

! 50
Window WIndoW
END

! 51
Window WIndOW
END

! 52
Window WIndOW
END

! 53
Window WInDoW
END

! 54
Window WInDoW
END

! 55
Window WInDOW
END

! 56
Window WInDOW
END

! 57
Window WINdoW
END

! 58
Window WINdoW
END

! 59
Window WINdOW
END

! 60
Window WINdOW
END

! 61
Window WINDoW
END

! 62
Window WINDoW
END

! 63
Window WINDOW
END

! 64
Window WINDOW
END
