 !Technical contents of ISO 4217, 1st revision 1981

 !For any additions or alterations to this list, please refer to the authoritative list maintained by the International Organization for Standardization. See ISO Online at http://www.iso.ch.

 !Currency and funds code list, Table 3, alphabetical by codes.

 !acct.  = account
 !conv.  = convertible
 !fin.   = financial
 !*      = no longer in use

United_Arab_Emirats                 ASTRING('AED')
Afghanistan                         ASTRING('AFA')
Albania                             ASTRING('ALL')
Netherlands_Antilles                ASTRING('ANG')
Angola                              ASTRING('AOK')
Argentina                           ASTRING('ARP')
Austria                             ASTRING('ATS')
Australia                           ASTRING('AUD')
  !Also includes
          !Christmas Island
          !Cocos (Keeling) Islands
          !Heard and McDonald Islands
          !Kiribati
          !Nauru
          !Norfolk Island
          !Tuvalu
Barbados                            ASTRING('BBD')
Bangladesh                          ASTRING('BDT')
Belgium_Franc_Conv                  ASTRING('BEC')
Belgian_Franc                       ASTRING('BEF')
Belgian_Franc_Fin                   ASTRING('BEL')
Bulgaria                            ASTRING('BGL')
Bahrain                             ASTRING('BHD')
Burundi                             ASTRING('BIF')
Burmuda                             ASTRING('BMD')
Brunei                              ASTRING('BND')
Bolivia                             ASTRING('BOP')
Brazil                              ASTRING('BRC')
Bahamas                             ASTRING('BSD')
Burma                               ASTRING('BUK')
Botswana                            ASTRING('BWP')
Belize                              ASTRING('BZD')
Canada                              ASTRING('CAD')
Switzerland                         ASTRING('CHF')
  !Also Includes
          !Liechtenstein
Chile                               ASTRING('CLP')
China                               ASTRING('CNY')
Colombia                            ASTRING('COP')
CostaRica                           ASTRING('CRC')
Czechoslovakia                      ASTRING('CSK')
Cuba                                ASTRING('CUP')
Cape_Verde                          ASTRING('CVE')
Cyprus                              ASTRING('CYP')
German_Democratic_Republic          ASTRING('DDM')
Federal_Republic_of_German          ASTRING('DEM')
Djibouti                            ASTRING('DJF')
Denmark                             ASTRING('DKK')
  !Also Includes
          !Faeroe Islands
          !Greenland
Dominican_Republic                  ASTRING('DOP')
Algeria                             ASTRING('DZD')
Ecuador                             ASTRING('ECS')
Egypt                               ASTRING('EGP')
Spain_Peseta_acct_A                 ASTRING('ESA*')
Spain_Peseta_acct_B                 ASTRING('ESB*')
Spain                               ASTRING('ESP')
  !Also Includes
          !Andorra
          !Western Sahara
Ethiopia                            ASTRING('ETB')
European_Union                      ASTRING('EUR')
Finland                             ASTRING('FIM')
Fiji                                ASTRING('FJD')
Falkland_Islands                    ASTRING('FKP')
France                              ASTRING('FRF')
  !Also Includes
          !Andorra
          !French Guiana
          !Guadeloupe
          !Martinique
          !Monaco
          !Reunion
          !St. Pierre and Miquelon
United_Kingdom                      ASTRING('GBP')
  !Also Includes
          !Canton and Enderbury Islands
Ghana                               ASTRING('GHC')
Gibraltar                           ASTRING('GIP')
Gambia                              ASTRING('GMD')
Guinea                              ASTRING('GNS')
Equatorial_Guinea                   ASTRING('GQE')
Greece                              ASTRING('GRD')
Guatemala                           ASTRING('GTQ')
Guinea_Bissau                       ASTRING('GWP')
Guyana                              ASTRING('GYD')
Hong_Kong                           ASTRING('HKD')
Honduras                            ASTRING('HNL')
Haiti                               ASTRING('HTG')
Hungary                             ASTRING('HUF')
Indonesia                           ASTRING('IDR')
Ireland                             ASTRING('IEP')
Israel                              ASTRING('ILS')
India                               ASTRING('INR')
  !Also Includes
          !Bhutan
Iraq                                ASTRING('IQD')
  !Also Includes
          !Neutral Zone (betw. Saudi A. & Iraq)
Iran                                ASTRING('IRR')
Iceland                             ASTRING('ISK')
Italy                               ASTRING('ITL')
  !Also Includes
          !San Marino
          !Vatican City State (Holy See)
Jamaica                             ASTRING('JMD')
Jordan                              ASTRING('JOD')
Japan                               ASTRING('JPY')
Kenya                               ASTRING('KES')
Democratic_Kampuchea                ASTRING('KHR')
Comoros                             ASTRING('KMF')
Democratic_peoples_of_Korea         ASTRING('KPW')
Republic_of_Korea                   ASTRING('KRW')
Kuwait                              ASTRING('KWD')
  !Also Includes
          !Neutral Zone (betw. Saudi A. & Iraq)
Cayman_Islands                      ASTRING('KYD')
Peoples_Democratic_Republic_of_Lao  ASTRING('LAK')
Lebanon                             ASTRING('LBP')
Sri_Lanka                           ASTRING('LKR')
Liberia                             ASTRING('LRD')
Lesotho                             ASTRING('LSM')
Luxembourg                          ASTRING('LUF')
Libyan_Arab_Jamahiriya              ASTRING('LYD')
Morocco                             ASTRING('MAD')
  !Also Includes
          !Western Sahara
Madagascar                          ASTRING('MGF')
Mali                                ASTRING('MLF')
Mongolia                            ASTRING('MNT')
Macau                               ASTRING('MOP')
Mauritania                          ASTRING('MRO')
  !Also Includes
          !Western Sahara
Malta                               ASTRING('MTP')
Mauritius                           ASTRING('MUR')
  !Also Includes
          !British Indian Ocean Territory
Maldives                            ASTRING('MVR')
Malawi                              ASTRING('MWK')
Mexico                              ASTRING('MXP')
Malaysia                            ASTRING('MYR')
Mozambique                          ASTRING('MZM')
Nigeria                             ASTRING('NGN')
Nicaragua                           ASTRING('NIC')
Netherlands                         ASTRING('NLG')
Norway                              ASTRING('NOK')
  !Also Includes
          !Bouvet Island
          !Dronning Maud Land
          !Antarctica
          !Svalbard and Jan Mayen Islands
Nepal                               ASTRING('NPR')
New_Zealand                         ASTRING('NZD')
  !Also Includes
          !Niue
          !Cook Islands
          !Pitcairn Island
          !Tokelau
Oman                                ASTRING('OMR')
Panama                              ASTRING('PAB')
Peru                                ASTRING('PES')
Papau_New_Guinea                    ASTRING('PGK')
Philippines                         ASTRING('PHP')
Pakistan                            ASTRING('PKR')
Poland                              ASTRING('PLZ')
Portugal                            ASTRING('PTE')
Paraguay                            ASTRING('PYG')
Qatar                               ASTRING('QAR')
Romania                             ASTRING('ROL')
Rwanda                              ASTRING('RWF')
Saudi_Arabia                        ASTRING('SAR')
  !Also Includes
          !Neutral Zone (betw. Saudi A. & Iraq)
Solomon_Islands                     ASTRING('SBD')
British_Indian_Ocean_Territory      ASTRING('SCR')
  !Also Includes
          !Seychelles
Sudan                               ASTRING('SDP')
Sweden                              ASTRING('SEK')
Singapore                           ASTRING('SGD')
St_Helena                           ASTRING('SHP')
Sierra_Leone                        ASTRING('SLL')
Somalia                             ASTRING('SOS')
Suriname                            ASTRING('SRG')
Sao_Tome_and_Principe               ASTRING('STD')
Union_of_Soviet_Socialist_Republics ASTRING('SUR')
  !Also Includes
          !Ukrainian SSR
          !Byelorussion SSR
El_Salvador                         ASTRING('SVC')
Syrian_Arab_Republic                ASTRING('SYP')
Swaziland                           ASTRING('SZL')
Thailand                            ASTRING('THB')
Tunisia                             ASTRING('TND')
Tonga                               ASTRING('TOP')
East_Timor                          ASTRING('TPE')
Turkey                              ASTRING('TRL')
Trinidad_and_Tobago                 ASTRING('TTD')
Province_of_China_Taiwan            ASTRING('TWD')
United_Republic_of_Tanzania         ASTRING('TZS')
Uganda                              ASTRING('UGS')
United_States                       ASTRING('USD')
  !Also Includes
          !British Virgin Islands
          !Canton and Enderbury Islands
          !Guam
          !Haiti
          !Johnston Island
          !Midway Islands
          !Pacific Islands (trush territory)
          !Panama
          !Puerto Rico
          !Turks and Caicos Islands
          !American Samoa
          !U.S. Miscellaneous Pacific Islands
          !U.S. Virgin Islands
          !Wake Island
United_States_Next_day              ASTRING('USN')
United_States_Same_day              ASTRING('USS*')
Uruguay                             ASTRING('UYP')
Viet_Nam                            ASTRING('VND')
Venezuela                           ASTRING('VEB')
Vanuatu                             ASTRING('VUV')
Samoa                               ASTRING('WST')
United_Republic_of_Cameroon         ASTRING('XAF')
  !Also Includes
          !Central African Republic
          !Chad
          !Congo
          !Gabon
Gold                                ASTRING('XAU')
European_Composite_Unit             ASTRING('XBA')
European_Monetary_Unit              ASTRING('XBB')
Euro_Unit_of_Acct_9                 ASTRING('XBC')
Euro_Unit_of_Acct_17                ASTRING('XBD')
Antiqua                             ASTRING('XCD')
  !Also Includes
          !Dominica
          !Grenada
          !Montserrat
          !St. Kitts-Nevis-Anguilla
          !Saint Lucia
          !Saint Vincent and the Grenadines
International_Monetary_Fund         ASTRING('XDR')
Euro_Monetary_Cooperation_Fund_EMCF ASTRING('XEU')
Benin                               ASTRING('XOF')
  !Also Includes
          !Ivory Coast
          !Niger
          !Senegal
          !Togo
          !Upper Volta
French_polynesia                    ASTRING('XPF')
  !Also Includes
          !New Caledonia
          !Wallis and Futuna Islands
No_Currency_Transaction             ASTRING('XXX')
Democratic_Yemen                    ASTRING('YDD')
Yemen                               ASTRING('YER')
Yugoslavia                          ASTRING('YUD')
South_Africa_Financial              ASTRING('ZAL')
South_Africa                        ASTRING('ZAR')
  !Also Includes
          !Namibia
          !Lesotho
Zambia                              ASTRING('ZMK')
Zaire                               ASTRING('ZRZ')
Zimbabwe                            ASTRING('ZWD')

  
